import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
  Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  records_sidebar: [
    'records/index',
    {
      type: 'category',
      label: 'Operating Systems Lab',
      collapsed: true,
      collapsible: true,
      items: [
        {type: 'autogenerated', dirName: 'records/os'},
      ],
    },
    {
      type: 'category',
      label: 'Database Management Lab',
      collapsed: true,
      collapsible: true,
      items: [
        {type: 'autogenerated', dirName: 'records/dbms'},
      ]
    },
    {
      type: 'category',
      label: 'Computer Networks Lab',
      collapsed: true,
      collapsible: true,
      items: [
        {type: 'autogenerated', dirName: 'records/cn'},
      ],
    },
  ],
};

export default sidebars;